#!/bin/bash 

function Help() {
    printf "\nUSAGE\n\n"
    echo "./run     [OPTION]        [INPUT_FILE_PATH]"
    echo "          -i | --image    input is an image"
    echo "          -v | --video    input is a video"
}

function Image() {
    # Check if the image is existed
    if [ ! -f ${input} ] ; then
        echo "File does not exist! Please check the file name again."
        exit -1
    fi

    echo "Converting ${input} to text file..."
    python3 Bitmap_Text_Converter.py ${input} > bitmap.in
    echo "Done converting!"

    echo "Simulating using ModelSim..."
    mv bitmap.in Verilog/bitmap.in
    # Change working directory to Verilog/
    cd Verilog/
    # -c option forces vsim to run in command-line mode (no GUI)
    vsim -c -do sim.do
    echo "Done simulating!"
    # Move bitmap.out out of Verilog/ directory
    mv bitmap.out ../bitmap.out
    # Return to the last working directory
    cd ../
    
    echo "Converting text output back to image..."
    python3 Text_Bitmap_Converter.py
    echo "Done converting!"

    echo "Converting using Python..."
    cd Python/
    python3 convert.py ${input}
    echo "Done converting!"

    echo "Showing images..."
    python3 compare.py ${input}

    exit 0
}

function Video() {
    # Check if the video is existed
    if [ ! -f ${input} ] ; then
        echo "File does not exist! Please check the file name again."
        exit -1
    fi
}

# Check if there is no argument
if [ $# -lt 1 ] ; then
    printf "Invalid argument! Require at least one argument.\n";
    exit -1;
fi

# Check if there is more than 2 arguments
if [ $# -gt 2 ] ; then
    printf "Two many arguments. Expect maximum of 2.\n";
    exit -1;
fi

# echo "Argument 0 is $0"
# echo "Argument 0 is $1"
# echo "Argument 0 is $2"

input=$2

# Check options correctness
case $1 in
  -i | --image)
    # printf "Option: input image.\n"
    Image
    exit 0
    ;;

  -v | --video)
    # printf "Option: input video.\n"
    Video
    exit 0
    ;;

  -h | --help)
    printf "Option: help\n"
    Help
    exit 0
    ;;

  *)
    printf "Option: not recognised\n"
    Help
    exit -1
    ;;
esac
